name: Bug Report
description: Report a bug or unexpected behavior
title: ""
body:
  - type: textarea
    id: current_behavior
    attributes:
      label: Current Behavior
      description: Describe the current behavior (using Gherkin format)
      placeholder: |
        Given [initial state]
        When [action]
        Then [incorrect outcome]
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: Describe the expected behavior (using Gherkin format)
      placeholder: |
        Given [initial state]
        When [action]
        Then [correct outcome]
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Provide detailed steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: records
    attributes:
      label: Logs/Screenshots
      description: Provide relevant logs, error messages, or screenshots
      placeholder: Paste logs or drag screenshots here

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Provide any other relevant information (version number, browser, environment details, etc.)
